### ISSUE TITLE
How do I install thundersvm without CUDA support?

### ISSUE THREAD

**Issue by VolodyaCO** [Xtra-Computing/thundersvm#219]
I installed thunderSVM for python via `pipenv install thundersvm`, which installed correctly. However, when I wanted to import SVM, I got the error:

```bash
>>> from thundersvm import SVM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vladimir/.local/share/virtualenvs/ICFES-SocioEconomico-x6jEQIYa/lib/python3.6/site-packages/thundersvm/__init__.py", line 10, in <module>
    from .thundersvm import *
  File "/home/vladimir/.local/share/virtualenvs/ICFES-SocioEconomico-x6jEQIYa/lib/python3.6/site-packages/thundersvm/thundersvm.py", line 39, in <module>
    thundersvm = CDLL(lib_path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.9.0: cannot open shared object file: No such file or directory
```

How can I import SVM so that it doesn't need CUDA support?

**Comment by zeyiwen** [comment]
Please follow the instructions in the documentation [working without GPUs](https://github.com/Xtra-Computing/thundersvm/blob/master/docs/get-started.md#working-without-gpus).
